export const testColumns = [
  { name: 'id', title: 'ID' },
  { name: 'product', title: 'Product' },
  { name: 'owner', title: 'Owner' },
  { name: 'column4', title: 'Column 4' },
  { name: 'column5', title: 'Column 5' },
  { name: 'column6', title: 'Column 6' },
  { name: 'column7', title: 'Column 7' },
  { name: 'column8', title: 'Column 8' },
  { name: 'column9', title: 'Column 9' },
  { name: 'column10', title: 'Column 10' },
  { name: 'column11', title: 'Column 11' },
  { name: 'column12', title: 'Column 12' },
  { name: 'column13', title: 'Column 13' },
  { name: 'column14', title: 'Column 14' },
  { name: 'column15', title: 'Column 15' },
];

export const testRows = [
  {
    id: 0,
    product: 'DevExtreme',
    owner: 'DevExpress',
    column4: 'Value 4',
    column5: 'Value 5',
    column6: 'Value 6',
    column7: 'Value 7',
    column8: 'Value 8',
    column9: 'Value 9',
    column10: 'Value 10',
    column11: 'Value 11',
    column12: 'Value 12',
    column13: 'Value 13',
    column14: 'Value 14',
    column15: 'Value 15',
  },
  {
    id: 1,
    product: 'DevExtreme Reactive',
    owner: 'DevExpress',
    column4: 'Value 4',
    column5: 'Value 5',
    column6: 'Value 6',
    column7: 'Value 7',
    column8: 'Value 8',
    column9: 'Value 9',
    column10: 'Value 10',
    column11: 'Value 11',
    column12: 'Value 12',
    column13: 'Value 13',
    column14: 'Value 14',
    column15: 'Value 15',
  },
  {
    id: 2,
    product: 'Another Product',
    owner: 'Another Owner',
    column4: 'Value 4',
    column5: 'Value 5',
    column6: 'Value 6',
    column7: 'Value 7',
    column8: 'Value 8',
    column9: 'Value 9',
    column10: 'Value 10',
    column11: 'Value 11',
    column12: 'Value 12',
    column13: 'Value 13',
    column14: 'Value 14',
    column15: 'Value 15',
  },
  {
    id: 3,
    product: 'Yet Another Product',
    owner: 'Yet Another Owner',
    column4: 'Value 4',
    column5: 'Value 5',
    column6: 'Value 6',
    column7: 'Value 7',
    column8: 'Value 8',
    column9: 'Value 9',
    column10: 'Value 10',
    column11: 'Value 11',
    column12: 'Value 12',
    column13: 'Value 13',
    column14: 'Value 14',
    column15: 'Value 15',
  },
  {
    id: 4,
    product: 'One More Product',
    owner: 'One More Owner',
    column4: 'Value 4',
    column5: 'Value 5',
    column6: 'Value 6',
    column7: 'Value 7',
    column8: 'Value 8',
    column9: 'Value 9',
    column10: 'Value 10',
    column11: 'Value 11',
    column12: 'Value 12',
    column13: 'Value 13',
    column14: 'Value 14',
    column15: 'Value 15',
  },
];
